---
- name: configure hypervisor
  become: true
  become_method: sudo
  hosts: hypervisors
  pre_tasks:
  - name: Configure hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
      use: systemd

  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: [ 'libvirt',
              'cockpit',
              'cockpit-machines'
            ]
      state: present

  - name: enable service(s)
    ansible.builtin.systemd_service:
      name: "{{ item }}"
      daemon_reload: true
      state: started
      enabled: true
    loop:
      - cockpit.socket
      - libvirtd
      - firewalld

  - name: open firewalld ports
    firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    loop:
      - cockpit

  post_tasks:
  - name: create guests
    ansible.builtin.include_tasks:
      file: tasks/configure_guests.yml
    loop: "{{ libvirt_guests }}"
    loop_control:
      label: "{{ item.name }}"
    tags:
    - guests

  handlers:
  - name: restart_libvirt
    service:
      name: libvirtd
      state: restarted

  - name: reboot_machine
    debug: msg='reboots'
