---
- name: Setup PreRequistits for a Kubernetes Cluster
  hosts: control_nodes
  become: true
  become_method: sudo
  pre_tasks:
    - name: fetch data
      ansible.builtin.slurp:
        src: /etc/kubernetes/admin.conf
      register: _kubernetes_config

    - name: set admin.conf data
      ansible.builtin.set_fact:
        _admin_conf: "{{ _kubernetes_config.content | b64decode | from_yaml }}"

    - name: set admin.conf data
      ansible.builtin.set_fact:
        _admin_conf_cluster: "{{ _admin_conf.clusters[0].cluster }}"
#        _admin_conf_server: "{{ _admin_conf.clusters[0].cluster.server }}"
#        _admin_conf_certificate_authority_data: "{{ _admin_conf.clusters[0].cluster.certificate-authority-data }}"

    - name: template
      connection: local
      become: false
      delegate_to: localhost
      ansible.builtin.template:
        src: .kube/config
        dest: ~/.kube/config