---
all:
  vars:
    ansible_user: nburr
  children:
    hypervisors:
      hosts:
        virt1: 
          ansible_host: 192.168.1.2
    control_nodes:
      hosts:
        control1:
          ansible_host: 192.168.1.21
    worker_nodes:
      hosts:
        worker1:
          ansible_host: 192.168.1.3
        worker2:
          ansible_host: 192.168.1.4
        worker3:
          ansible_host: 192.168.1.5
    kubernetes:
      children:
        control_nodes:
        worker_nodes:
      cluster1:
      cluster2:
      cluster3: