---
all:
  vars:
    ansible_user: nburr
  children:
    hypervisors:
      hosts:
        virt1: 
          ansible_host: 192.168.1.2
    dns:
      hosts:
        ns1:
          ansible_host: 192.168.1.21
    nfs:
      hosts:
        nfs:
          ansible_host: 192.168.1.22
#    control_nodes:
#      hosts:
#        aio-cluster1:
#          ansible_host: 192.168.1.30
#        aio-cluster2:
#          ansible_host: 192.168.1.40
#        aio-cluster3:
#          ansible_host: 192.168.1.50
    worker_nodes:
      hosts:
        aio-cluster1:
          ansible_host: 192.168.1.30
        aio-cluster2:
          ansible_host: 192.168.1.40
        aio-cluster3:
          ansible_host: 192.168.1.50
    kubernetes:
      children:
        control_nodes:
        worker_nodes:
