---
- name: configure zones
  ansible.builtin.template:
    src: templates/var/named/{{ item.zone }}.zone
    dest: /var/named/{{ item.zone }}.zone
    mode: 0640
    owner: root
    group: named
    backup: true
  register: _named_zone
  notify: _reload_named


- name: validate named.conf
  block:
  - name:
    ansible.builtin.shell: "named-checkzone {{ item.zone }} {{ _named_zone.dest }}"
    changed_when: false
    failed_when: _named_checkzone.rc != 0
    register: _named_checkzone
    when: _named_zone.changed

  rescue:
  - name: restore /etc/named.conf
    ansible.builtin.copy:
      src: "{{ _named_zone.backup_file }}"
      dest: "{{ _named_zone.dest }}"
      remote_src: yes
  - name: /etc/named.conf is invlaid.
    fail: 
      msg: "named zone: {{ item.zone }} is not valid - {{ _named_checkzone.stdout }}"