---
- name: "Initialize Master - {{ kubernetes_x_stream }}.{{ kubernetes_y_stream }}.{{ kubernetes_z_stream }}"
  ansible.builtin.command: "kubeadm init \
           --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
           --kubernetes-version={{ kubernetes_x_stream }}.{{ kubernetes_y_stream }}.{{ kubernetes_z_stream }} \
           --pod-network-cidr={{ kubernetes_pod_network_cidr }}"
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubernetes_master_initalized
# The 'creates' arg does not accept a list; these file(s) are what kubeadm is  checking for
#    - /etc/kubernetes/manifests/etcd.yaml
#    - /etc/kubernetes/manifests/kube-apiserver.yaml
#    - /etc/kubernetes/manifests/kube-controller-manager.yaml
#    - /etc/kubernetes/manifests/kube-scheduler.yaml

- name: clone manifests repository
  ansible.builtin.git:
    repo: 'https://github.com/nicholasburr/lab-kustomize.git'
    dest: /tmp/lab-kustomize
  register: _manifests_repository

#  msg: |-
#    kustomize command failed with: Error: must build at directory: not a valid directory: evalsymlink failure on '/tmp/lab-kustomize/flannel/base/' : lstat /private/tmp/lab-kustomize: no such file or directory
#- name: Initalize CNI
#  kubernetes.core.k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='/tmp/lab-kustomize/flannel/base/') }}"
#    kubeconfig: /etc/kubernetes/admin.conf
#    state: present

- name: Initalize CNI
  ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -k /tmp/lab-kustomize/flannel/base/