---
apiVersion: v1
data:
  certificate: {{  _kubernetes_user_csr_info.resources[0].status.certificate | b64encode }}
kind: Secret
metadata:
  name: {{ kubernetes_user }}-auth
  namespace: kube-auth
type: Opaque